import type { Category, Center, CommunityInitiative, CommunityPost, Listing, Municipality, Provider, Review } from "./types";

export const municipalities: Municipality[] = [
  { id: "las-rozas", name: "Las Rozas de Madrid", slug: "las-rozas", description: "Colegios, guarderías, uniformes, actividades y servicios para familias en Las Rozas de Madrid." },
  { id: "majadahonda", name: "Majadahonda", slug: "majadahonda", description: "Recursos familiares cercanos para familias de Majadahonda y Madrid noroeste." },
  { id: "pozuelo", name: "Pozuelo de Alarcón", slug: "pozuelo", description: "Directorio local para familias con centros educativos en Pozuelo de Alarcón." },
  { id: "boadilla", name: "Boadilla del Monte", slug: "boadilla", description: "Recursos próximos al colegio para familias de Boadilla del Monte." }
];

export const categories: Category[] = [
  { id: "uniformes", name: "Uniformes", slug: "uniformes", description: "Uniformes escolares, prendas y reutilización segura por zona y centro orientativo.", seoTitle: "Uniformes escolares cerca de tu centro | Kiryco", seoDescription: "Encuentra uniformes escolares en buen estado cerca de tu zona y centro educativo, con publicaciones moderadas." },
  { id: "libros-material", name: "Libros y material", slug: "libros-material", description: "Libros, material escolar, calzado y lotes por etapa educativa sin identificar a menores.", seoTitle: "Libros y material escolar cerca de ti | Kiryco", seoDescription: "Localiza libros, material escolar, calzado y lotes por municipio, edad recomendada y centro orientativo." },
  { id: "clases-particulares", name: "Clases particulares", slug: "clases-particulares", description: "Profesores, academias e idiomas para apoyo escolar, ciencias, arte y exámenes.", seoTitle: "Clases particulares en Las Rozas | Kiryco", seoDescription: "Encuentra clases particulares por materia, modalidad, municipio y nivel educativo recomendado." },
  { id: "canguros", name: "Canguros", slug: "canguros", description: "Canguros y babysitters con experiencia, disponibilidad general y referencias verificables.", seoTitle: "Canguros y babysitters en Las Rozas | Kiryco", seoDescription: "Busca canguros por zona, edad recomendada, disponibilidad general y verificación." },
  { id: "extraescolares", name: "Extraescolares", slug: "extraescolares", description: "Actividades, deporte, clubes, creatividad, música, tecnología e idiomas para distintas edades.", seoTitle: "Extraescolares y deporte cerca del colegio | Kiryco", seoDescription: "Descubre actividades extraescolares por zona, edad recomendada, precio y disponibilidad." },
  { id: "centros", name: "Centros educativos", slug: "centros", description: "Fichas estructuradas de colegios, escuelas infantiles e institutos con información pública.", seoTitle: "Colegios y centros educativos en Las Rozas | Kiryco", seoDescription: "Consulta colegios y centros educativos con información pública, etapas, servicios, etiquetas y reseñas moderadas." }
];

const base = ["Las Rozas de Madrid", "Madrid noroeste", "Familias"];
const centerImage = "/images/cards/centro-educativo.svg";
const serviceImage = "/images/cards/servicio-familiar.svg";
const activityImage = "/images/cards/actividad.svg";
const productImage = "/images/cards/producto.svg";

export const centers: Center[] = [
  { id: "el-cantizal", slug: "colegio-el-cantizal", name: "Colegio El Cantizal", type: "publico", religiousCharacter: "laico", stages: ["Infantil", "Primaria", "ESO"], municipality: "Las Rozas de Madrid", address: "Avenida de Atenas s/n, 28232 Las Rozas de Madrid", phone: "91 603 00 99", email: "cp.elcantizal.lasrozas@educa.madrid.org", website: "https://www.colegioelcantizal.es/", languages: ["Inglés"], services: ["Comedor", "Horario ampliado", "Extraescolares", "AMPA"], description: "CEIPSO público bilingüe situado en El Cantizal, con etapas de infantil, primaria y secundaria obligatoria inicial.", source: "Web oficial", sourceUrl: "https://www.colegioelcantizal.es/el-colegio/donde-estamos/", tags: [...base, "Público", "CEIPSO", "Bilingüe", "El Cantizal", "Comedor", "Horario ampliado"], image: centerImage, verified: true },
  { id: "los-jarales", slug: "colegio-los-jarales-monterrozas", name: "Colegio Los Jarales - Monterrozas", type: "publico", religiousCharacter: "laico", stages: ["Infantil", "Primaria", "ESO progresiva"], municipality: "Las Rozas de Madrid", address: "Calle Ramón y Cajal, 1, 28232 Las Rozas de Madrid", phone: "91 631 84 90 / 639 668 344", email: "cp.losjarales.lasrozas@educa.madrid.org", website: "https://www.educa2.madrid.org/web/centro.cp.losjarales.lasrozas", languages: ["Inglés"], services: ["Comedor", "Horario ampliado", "Extraescolares", "Transporte escolar"], description: "Centro público bilingüe de Monterrozas con infantil, primaria y extensión progresiva a ESO.", source: "EducaMadrid", sourceUrl: "https://www.educa2.madrid.org/web/centro.cp.losjarales.lasrozas/contacto", tags: [...base, "Público", "CEIPSO", "Bilingüe", "Monterrozas", "Transporte escolar"], image: centerImage, verified: true },
  { id: "la-encina", slug: "colegio-la-encina", name: "Colegio La Encina", type: "publico", religiousCharacter: "laico", stages: ["Infantil", "Primaria"], municipality: "Las Rozas de Madrid", address: "Calle Ramón y Cajal, 3, 28232 Las Rozas de Madrid", phone: "91 640 37 25", email: "cp.laencina.lasrozas@educa.madrid.org", website: "https://www.educa2.madrid.org/web/centro.cp.laencina.lasrozas", languages: ["Inglés"], services: ["Comedor", "Horario ampliado", "Extraescolares", "AMPA"], description: "Colegio público bilingüe de educación infantil y primaria en Las Rozas.", source: "EducaMadrid", sourceUrl: "https://www.educa2.madrid.org/web/centro.cp.laencina.lasrozas/inicio/-/visor/contacto", tags: [...base, "Público", "CEIP", "Bilingüe", "Infantil", "Primaria", "AMPA"], image: centerImage, verified: true },
  { id: "berriz-veracruz", slug: "colegio-berriz-veracruz", name: "Colegio Berriz - Veracruz", type: "concertado", religiousCharacter: "catolico", stages: ["Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Camino Real, 3, 28230 Las Rozas de Madrid", phone: "91 630 37 33 / 91 630 15 00", email: "secretaria@colegioberriz.com", website: "https://colegioberriz.com/", languages: ["Inglés"], services: ["Comedor", "Transporte escolar", "Extraescolares"], description: "Centro privado-concertado católico y bilingüe con etapas desde infantil hasta bachillerato.", source: "BuscoColegio", sourceUrl: "https://www.buscocolegio.com/School/school-details.action?id=28024186", tags: [...base, "Concertado", "Católico", "Bilingüe", "Bachillerato", "Transporte escolar"], image: centerImage, verified: true },
  { id: "gredos-san-diego", slug: "colegio-gredos-san-diego-las-rozas", name: "Colegio Gredos San Diego", type: "concertado", religiousCharacter: "laico", stages: ["Infantil", "Primaria", "ESO", "Bachillerato", "Formación Profesional"], municipality: "Las Rozas de Madrid", address: "Calle Clara Campoamor, 1, 28232 Las Rozas de Madrid", phone: "91 640 89 23", email: "lasrozas@gsdeducacion.com", website: "https://www.gsdeducacion.com/", languages: ["Inglés"], services: ["Comedor", "Extraescolares", "Formación Profesional", "Orientación"], description: "Centro concertado laico y bilingüe de la red GSD, con etapas escolares y formación profesional.", source: "Comunidad de Madrid", sourceUrl: "https://www.comunidad.madrid/centros/centro-gredos-san-diego-rozas", tags: [...base, "Concertado", "Laico", "Bilingüe", "Cooperativa", "FP"], image: centerImage, verified: true },
  { id: "zola", slug: "colegio-zola-las-rozas", name: "Colegio Zola", type: "concertado", religiousCharacter: "laico", stages: ["Escuela infantil", "Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Avenida de Esparta, 6, 28232 Las Rozas de Madrid", phone: "91 631 62 53", email: "secretaria@colegioszola.es", website: "https://colegiozolalasrozas.es/", languages: ["Inglés", "Alemán"], services: ["Comedor", "Extraescolares", "Horario ampliado", "Piscina", "Robótica"], description: "Colegio concertado laico con proyecto internacional, foco en inglés y alemán y continuidad hasta bachillerato.", source: "Web oficial", sourceUrl: "https://colegiozolalasrozas.es/contacto/", tags: [...base, "Concertado", "Laico", "Inglés", "Alemán", "Internacional", "Robótica", "Piscina"], image: centerImage, verified: true },
  { id: "europeo-madrid", slug: "colegio-europeo-de-madrid", name: "Colegio Europeo de Madrid", type: "privado", religiousCharacter: "laico", stages: ["Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Calle Cólquide, 14, 28231 Las Rozas de Madrid", phone: "91 636 19 19", email: "admisionescem@cognita.com", website: "https://www.colegioeuropeodemadrid.com/", languages: ["Inglés", "Francés", "Alemán", "Chino"], services: ["Comedor", "Extraescolares", "Horario ampliado", "Orientación"], description: "Colegio privado laico y bilingüe en Las Rozas, integrado en Cognita, con orientación internacional.", source: "Web oficial", sourceUrl: "https://www.colegioeuropeodemadrid.com/contactanos/", tags: [...base, "Privado", "Laico", "Bilingüe", "Internacional", "Cognita"], image: centerImage, verified: true },
  { id: "balder", slug: "colegio-balder", name: "Colegio Balder", type: "privado", religiousCharacter: "laico", stages: ["Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Calle Sierra Morena, 41, 28290 Las Rozas de Madrid", phone: "91 630 32 32", email: "info@colegiobalder.com", website: "https://colegiobalder.com/", languages: ["Inglés", "Francés", "Alemán", "Chino"], services: ["Comedor", "Horario ampliado", "Extraescolares", "Admisiones"], description: "Colegio privado de Las Rozas con infantil, primaria, secundaria y bachillerato.", source: "Web oficial", sourceUrl: "https://colegiobalder.com/contacto/", tags: [...base, "Privado", "Laico", "Idiomas", "Horario ampliado", "Sierra Morena"], image: centerImage, verified: true },
  { id: "orvalle", slug: "colegio-orvalle", name: "Colegio Orvalle", type: "privado", religiousCharacter: "catolico", stages: ["Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Avenida de Andraitx, 1, 28290 Las Rozas de Madrid", phone: "91 631 96 79", email: "orvalle@orvalle.es", website: "https://www.orvalle.es/", languages: ["Inglés"], services: ["Transporte escolar", "Comedor", "Extraescolares", "Orientación"], description: "Colegio privado católico y bilingüe en Las Rozas, con continuidad educativa y rutas de transporte.", source: "Web oficial", sourceUrl: "https://www.orvalle.es/contacto/", tags: [...base, "Privado", "Católico", "Bilingüe", "Transporte escolar", "Andraitx"], image: centerImage, verified: true },
  { id: "logos", slug: "colegio-logos", name: "Colegio Logos", type: "privado", religiousCharacter: "laico", stages: ["Escuela infantil", "Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "C/ Juníperos, 6 y C/ del Sacre, 2, 28232 Las Rozas de Madrid", phone: "91 603 18 06 / 91 630 34 94", email: "colegio@colegiologos.com", website: "https://logosinternationalschool.es/", languages: ["Inglés", "Francés", "Alemán", "Chino"], services: ["Comedor", "Horario ampliado", "Extraescolares", "Escuela infantil"], description: "Colegio privado bilingüe con sedes de escuela infantil y colegio en Las Rozas.", source: "Web oficial", sourceUrl: "https://logosnurseryschool.es/nursery/contact/", tags: [...base, "Privado", "Bilingüe", "Internacional", "Escuela infantil", "El Cantizal", "Molino de la Hoz"], image: centerImage, verified: true },
  { id: "santa-maria", slug: "colegio-santa-maria-las-rozas", name: "Colegio Santa María", type: "concertado", religiousCharacter: "catolico", stages: ["Infantil", "Primaria", "ESO"], municipality: "Las Rozas de Madrid", address: "C/ Madre María Dolores Segarra, 1, 28231 Las Rozas de Madrid", phone: "91 637 66 61", email: "colegio@santamariadelasrozas.es", website: "https://santamariadelasrozas.com/", languages: ["Inglés"], services: ["Comedor", "Orientación", "Extraescolares", "Capilla"], description: "Colegio católico concertado en Las Rozas con infantil, primaria y ESO.", source: "Web oficial", sourceUrl: "https://santamariadelasrozas.com/", tags: [...base, "Concertado", "Católico", "Infantil", "Primaria", "ESO", "Orientación"], image: centerImage, verified: true },
  { id: "punta-galea", slug: "colegio-punta-galea", name: "Colegio Punta Galea", type: "concertado", religiousCharacter: "no indicado", stages: ["Infantil", "Primaria", "ESO", "Bachillerato"], municipality: "Las Rozas de Madrid", address: "Calle Playa del Sardinero, 1, 28290 Las Rozas de Madrid", phone: "91 630 26 41 / 91 630 29 14", email: "cepg@colegio-puntagalea.com", website: "https://colegio-puntagalea.com/", languages: ["Inglés"], services: ["Comedor", "Horario ampliado", "Extraescolares", "Natación"], description: "Centro educativo Punta Galea con infantil, primaria, secundaria y bachillerato.", source: "Web oficial", sourceUrl: "https://colegio-puntagalea.com/informacion-a-las-familias/", tags: [...base, "Concertado", "Punta Galea", "Bachillerato", "Natación", "Comedor"], image: centerImage, verified: true }
];

const providerSeeds = [
  ["guarderia-trazos", "Escuela Infantil Trazos", "Guardería", "Guardería", "0-3, conciliación, escuela infantil"], ["guarderia-nubes", "Escuela Infantil Nubes", "Guardería", "Guardería", "0-3, El Cantizal, horario ampliado"], ["guarderia-bosque", "Escuela Infantil Bosque Claro", "Guardería", "Guardería", "0-3, Punta Galea, comedor"], ["guarderia-peques", "Peques Monterrozas", "Guardería", "Guardería", "0-3, Monterrozas, conciliación"],
  ["deporte-cantizal", "Centro Municipal El Cantizal", "Deporte infantil", "Extraescolares", "deporte, municipal, piscina, escuelas deportivas"], ["padel-rozas", "Escuela de Pádel Las Rozas", "Deporte infantil", "Extraescolares", "pádel, niños, tardes"], ["natacion-rozas", "Escuela de Natación Las Rozas", "Deporte infantil", "Extraescolares", "natación, piscina, seguridad acuática"], ["futbol-rozas", "Escuela de Fútbol Noroeste", "Deporte infantil", "Extraescolares", "fútbol, equipo, valores"], ["basket-rozas", "Baloncesto Las Rozas Escuela", "Deporte infantil", "Extraescolares", "baloncesto, equipo, secundaria"], ["tenis-rozas", "Tenis Monte Rozas", "Deporte infantil", "Extraescolares", "tenis, Monte Rozas, grupo"], ["judo-rozas", "Judo Las Rozas Kids", "Deporte infantil", "Extraescolares", "judo, disciplina, coordinación"], ["danza-rozas", "Danza Noroeste", "Deporte infantil", "Extraescolares", "danza, movimiento, creatividad"], ["voley-rozas", "Voleibol Las Rozas", "Deporte infantil", "Extraescolares", "voleibol, equipo, adolescentes"], ["patinaje-rozas", "Patinaje Las Rozas", "Deporte infantil", "Extraescolares", "patinaje, equilibrio, iniciación"],
  ["robotica-rozas", "Robótica Noroeste", "Extraescolares", "Extraescolares", "robótica, programación, STEAM"], ["ingles-rozas", "Inglés Las Rozas", "Idiomas", "Clases", "inglés, Cambridge, conversación"], ["musica-rozas", "Música en Familia Las Rozas", "Extraescolares", "Extraescolares", "música, piano, guitarra"], ["arte-rozas", "Taller de Arte Las Rozas", "Extraescolares", "Extraescolares", "arte, pintura, dibujo"], ["teatro-rozas", "Teatro Joven Las Rozas", "Extraescolares", "Extraescolares", "teatro, expresión oral, confianza"], ["ajedrez-rozas", "Ajedrez Escolar Noroeste", "Extraescolares", "Extraescolares", "ajedrez, concentración, estrategia"], ["debate-rozas", "Oratoria y Debate Las Rozas", "Extraescolares", "Extraescolares", "oratoria, debate, comunicación"], ["ciencia-rozas", "Ciencia Divertida Las Rozas", "Extraescolares", "Extraescolares", "ciencia, experimentos, STEAM"], ["lectura-rozas", "Club de Lectura Infantil", "Extraescolares", "Extraescolares", "lectura, escritura, comprensión"], ["ceramica-rozas", "Cerámica Creativa Las Rozas", "Extraescolares", "Extraescolares", "cerámica, manualidades, creatividad"],
  ["papeleria-rozas", "Papelería Escolar Las Rozas", "Material escolar", "Libros y material", "papelería, mochilas, vuelta al cole"], ["uniformes-rozas", "Uniformes Noroeste", "Uniformes", "Uniformes", "uniformes, arreglos, ropa escolar"], ["calzado-rozas", "Calzado Infantil Noroeste", "Calzado escolar", "Libros y material", "calzado, deportivas, zapatos"], ["libreria-rozas", "Librería Noroeste", "Libros y material", "Libros y material", "libros, cuadernos, lecturas"], ["logopedia-rozas", "Logopedia Las Rozas", "Servicio familiar", "Clases", "logopedia, lenguaje, apoyo"], ["optica-rozas", "Óptica Familiar Las Rozas", "Servicio familiar", "Libros y material", "óptica, salud visual, escolar"], ["fundacion-syei", "Fundación SyEi", "Servicio familiar", "Clases", "salud integral, educación integral, logopedia, psicología, terapia ocupacional, Las Rozas"],
  ["canguro-ana", "Ana M.", "Canguros", "Canguros", "canguro, tardes, referencias"], ["canguro-laura", "Laura R.", "Canguros", "Canguros", "canguro, Punta Galea, tardes"], ["canguro-marta", "Marta S.", "Canguros", "Canguros", "babysitter, fin de semana, puntual"], ["canguro-pablo", "Pablo T.", "Canguros", "Canguros", "canguro, acompañamiento, tardes"]
] as const;

export const providers: Provider[] = providerSeeds.map(([id, businessName, category, shortCategory, rawTags]) => ({ id, userId: id, businessName, category, description: id === "fundacion-syei" ? "Fundación SyEi, Salud y Educación Integrales en Las Rozas, ofrece atención terapéutica integral con psicología, logopedia, psicopedagogía, fisioterapia, optometría, terapia visual y acompañamiento familiar desde una mirada 360 grados." : `${businessName}: perfil inicial para búsquedas de ${shortCategory.toLowerCase()} en Las Rozas, con contacto adulto y datos protegidos.`, municipality: id === "calzado-rozas" ? "Majadahonda" : "Las Rozas de Madrid", serviceArea: id === "calzado-rozas" ? "Majadahonda, Las Rozas y Pozuelo" : "Las Rozas de Madrid y alrededores", website: id === "deporte-cantizal" ? "https://www.lasrozas.es/deportes/instalaciones/centrocantizal" : id === "fundacion-syei" ? "https://www.saludyeducacionintegrales.org/" : "https://example.com", phone: id === "deporte-cantizal" ? "91 757 98 40" : id === "fundacion-syei" ? "91 724 20 30" : id.startsWith("canguro") ? "Contacto protegido" : "Consultar", email: id === "deporte-cantizal" ? "deportes@lasrozas.es" : id === "fundacion-syei" ? "Contacto desde web oficial" : id.startsWith("canguro") ? "Contacto protegido" : "contacto@example.com", verified: id === "deporte-cantizal" || id === "fundacion-syei", plan: id === "deporte-cantizal" || id === "robotica-rozas" || id === "fundacion-syei" ? "destacado" : "gratuito", tags: rawTags.split(", ").concat(["Las Rozas", "Familias"]), image: id === "fundacion-syei" ? serviceImage : undefined }));

function provider(id: string) { return providers.find((item) => item.id === id)!; }
function imageFor(categoryId: string) { if (categoryId === "centros") return centerImage; if (categoryId === "extraescolares") return activityImage; if (categoryId === "uniformes" || categoryId === "libros-material") return productImage; return serviceImage; }
function makeListing(id: string, categoryId: string, title: string, providerId: string, ageMin: number, ageMax: number, priceLabel = "Consultar", area = "Las Rozas"): Listing { const item = provider(providerId); return { id, slug: id, userId: providerId, categoryId, title, description: id === "fundacion-syei-las-rozas" ? "Centro de salud y educación integrales en Las Rozas con enfoque interdisciplinar para niños, adolescentes, adultos y familias: psicología, logopedia, psicopedagogía, terapia visual, fisioterapia, atención temprana y acompañamiento educativo familiar." : `${title} en ${area}. Recurso local orientado a familias, con información general por edad y sin datos personales de menores.`, municipality: item.municipality, area, recommendedAgeMin: ageMin, recommendedAgeMax: ageMax, priceLabel, availability: "Consultar disponibilidad", publicationType: "proveedor", status: "published", verified: item.verified, tags: item.tags, image: item.image ?? imageFor(categoryId), details: { proveedor: item.businessName, zona: area, contacto: item.phone } }; }

export const listings: Listing[] = [
  ...centers.map((center) => ({ id: `ficha-${center.id}`, slug: center.slug, userId: "kiryco", categoryId: "centros", centerId: center.id, title: center.name, description: center.description, municipality: center.municipality, area: center.tags.includes("El Cantizal") ? "El Cantizal" : center.tags.includes("Monterrozas") ? "Monterrozas" : center.tags.includes("Punta Galea") ? "Punta Galea" : "Las Rozas", recommendedAgeMin: 1, recommendedAgeMax: 18, priceLabel: "Consultar centro", availability: "Ficha pública", publicationType: "centro" as const, status: "published" as const, verified: center.verified, tags: center.tags, image: center.image ?? centerImage, details: { tipo: center.type, etapas: center.stages.join(", "), fuente: center.source } })),
  makeListing("escuela-infantil-trazos", "centros", "Escuela Infantil Trazos", "guarderia-trazos", 0, 3), makeListing("escuela-infantil-nubes", "centros", "Escuela Infantil Nubes", "guarderia-nubes", 0, 3, "Consultar", "El Cantizal"), makeListing("escuela-infantil-bosque-claro", "centros", "Escuela Infantil Bosque Claro", "guarderia-bosque", 0, 3, "Consultar", "Punta Galea"), makeListing("peques-monterrozas", "centros", "Peques Monterrozas", "guarderia-peques", 0, 3, "Consultar", "Monterrozas"),
  makeListing("centro-municipal-el-cantizal", "extraescolares", "Actividades deportivas en Centro Municipal El Cantizal", "deporte-cantizal", 4, 16, "Según actividad", "El Cantizal"), makeListing("padel-las-rozas-kids", "extraescolares", "Clases de pádel para niños", "padel-rozas", 7, 16, "Desde 45 €/mes"), makeListing("natacion-infantil-las-rozas", "extraescolares", "Natación infantil por niveles", "natacion-rozas", 3, 14), makeListing("futbol-base-noroeste", "extraescolares", "Fútbol base en Las Rozas", "futbol-rozas", 6, 16), makeListing("baloncesto-las-rozas", "extraescolares", "Baloncesto escolar", "basket-rozas", 8, 16), makeListing("tenis-monte-rozas", "extraescolares", "Tenis infantil y juvenil", "tenis-rozas", 6, 16, "Consultar", "Monte Rozas"), makeListing("judo-las-rozas-kids", "extraescolares", "Judo infantil", "judo-rozas", 5, 14), makeListing("danza-noroeste", "extraescolares", "Danza y movimiento", "danza-rozas", 4, 16), makeListing("voleibol-las-rozas", "extraescolares", "Voleibol para adolescentes", "voley-rozas", 10, 18), makeListing("patinaje-las-rozas", "extraescolares", "Patinaje de iniciación", "patinaje-rozas", 5, 14),
  makeListing("robotica-noroeste", "extraescolares", "Robótica y programación", "robotica-rozas", 7, 16, "Desde 49 €/mes"), makeListing("ingles-las-rozas", "clases-particulares", "Inglés por niveles", "ingles-rozas", 6, 18, "Desde 55 €/mes"), makeListing("musica-en-familia", "extraescolares", "Música, piano y guitarra", "musica-rozas", 5, 18), makeListing("taller-arte-las-rozas", "extraescolares", "Dibujo y pintura", "arte-rozas", 4, 16), makeListing("teatro-joven-las-rozas", "extraescolares", "Teatro y expresión oral", "teatro-rozas", 7, 16), makeListing("ajedrez-escolar-noroeste", "extraescolares", "Ajedrez escolar", "ajedrez-rozas", 6, 16), makeListing("oratoria-debate-las-rozas", "extraescolares", "Oratoria y debate", "debate-rozas", 12, 18), makeListing("ciencia-divertida-las-rozas", "extraescolares", "Talleres de ciencia", "ciencia-rozas", 6, 14), makeListing("club-lectura-infantil", "extraescolares", "Club de lectura y escritura", "lectura-rozas", 6, 14), makeListing("ceramica-creativa-las-rozas", "extraescolares", "Cerámica y manualidades", "ceramica-rozas", 5, 14),
  makeListing("papeleria-escolar-las-rozas", "libros-material", "Material escolar y papelería", "papeleria-rozas", 3, 18), makeListing("uniformes-noroeste", "uniformes", "Uniformes y arreglos escolares", "uniformes-rozas", 3, 18), makeListing("calzado-escolar-noroeste", "libros-material", "Calzado escolar e infantil", "calzado-rozas", 3, 16, "Consultar", "Majadahonda"), makeListing("libreria-noroeste", "libros-material", "Libros de lectura y cuadernos", "libreria-rozas", 3, 18), makeListing("logopedia-las-rozas", "clases-particulares", "Logopedia y apoyo al lenguaje", "logopedia-rozas", 3, 14), makeListing("optica-familiar-las-rozas", "libros-material", "Óptica familiar", "optica-rozas", 3, 18), makeListing("fundacion-syei-las-rozas", "clases-particulares", "Fundación SyEi: salud y educación integrales", "fundacion-syei", 1, 18, "Consultar", "Avenida del Polideportivo"),
  makeListing("canguro-ana-m", "canguros", "Canguro con experiencia en tardes", "canguro-ana", 3, 12, "12-15 €/hora", "El Cantizal"), makeListing("canguro-laura-r", "canguros", "Canguro para tardes en Punta Galea", "canguro-laura", 4, 14, "Consultar", "Punta Galea"), makeListing("canguro-marta-s", "canguros", "Babysitter para fines de semana", "canguro-marta", 2, 10, "Consultar"), makeListing("canguro-pablo-t", "canguros", "Canguro para apoyo de tarde", "canguro-pablo", 6, 14, "Consultar")
];

export const communityInitiatives: CommunityInitiative[] = [{ id: "bpan-matters", name: "BPAN Matters", url: "https://bpanmatters.org/", municipality: "Iniciativa internacional con interés para familias de la zona", summary: "Iniciativa de sensibilización sobre BPAN, una enfermedad rara vinculada al gen WDR45 y al grupo de neurodegeneración con acumulación cerebral de hierro. Kiryco la incorpora como recurso comunitario para dar visibilidad a causas familiares, investigación y apoyo entre familias.", tags: ["BPAN", "Enfermedades raras", "WDR45", "Neurodegeneración", "Familias", "Investigación", "Sensibilización"], image: "/images/cards/comunidad.svg", ctaLabel: "Conocer BPAN Matters" }];
export const searchTags = Array.from(new Set([...centers.flatMap((center) => center.tags), ...listings.flatMap((item) => item.tags), ...providers.flatMap((item) => item.tags), ...communityInitiatives.flatMap((item) => item.tags)])).sort((a, b) => a.localeCompare(b, "es"));
export const reviews: Review[] = [ { id: "r-el-cantizal", centerId: "el-cantizal", ratingCommunication: 4, ratingFacilities: 4, ratingEnvironment: 4, ratingActivities: 4, ratingLanguages: 4, ratingAttention: 4, comment: "Resumen editorial moderado: ficha pública útil para comparar etapas, servicios y contacto oficial. Las valoraciones familiares reales se publicarán solo tras revisión.", status: "published" }, { id: "r-zola", centerId: "zola", ratingCommunication: 4, ratingFacilities: 5, ratingEnvironment: 4, ratingActivities: 5, ratingLanguages: 5, ratingAttention: 4, comment: "Resumen editorial moderado: destaca por variedad de idiomas, escuela infantil y oferta de extraescolares. No sustituye la visita ni la información oficial del centro.", status: "published" }, { id: "r-orvalle", centerId: "orvalle", ratingCommunication: 4, ratingFacilities: 4, ratingEnvironment: 4, ratingActivities: 4, ratingLanguages: 5, ratingAttention: 4, comment: "Resumen editorial moderado: ficha orientada a familias que comparan proyecto católico, transporte escolar y continuidad educativa.", status: "published" } ];
export const communityPosts: CommunityPost[] = [ { id: "c1", title: "Dónde encontrar uniformes y arreglos en Las Rozas", category: "Uniformes", municipality: "Las Rozas de Madrid", summary: "Pregunta revisada sobre alternativas de compra y arreglos sin datos de menores.", status: "published" }, { id: "c2", title: "Extraescolares de robótica, música y deporte por zonas", category: "Extraescolares", municipality: "Las Rozas de Madrid", summary: "Hilo moderado con opciones por edad recomendada y zona.", status: "published" }, { id: "c3", title: "Consulta sobre intercambio de libros y material", category: "Libros y material", municipality: "Las Rozas de Madrid", summary: "Pendiente de revisión antes de aparecer públicamente.", status: "pending_review" } ];
export function findCategory(slug: string) { return categories.find((category) => category.slug === slug); }
export function findListing(slugOrId: string) { return listings.find((listing) => listing.slug === slugOrId || listing.id === slugOrId); }
export function findCenter(slug: string) { return centers.find((center) => center.slug === slug); }
export function ageLabel(listing: Listing) { if (!listing.recommendedAgeMin && !listing.recommendedAgeMax) return "Edad orientativa no indicada"; return `${listing.recommendedAgeMin ?? 1}-${listing.recommendedAgeMax ?? 18} años`; }
